PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT ?version ?dataset_uri ?issued (SAMPLE(?distribution_uri) AS ?distribution_uri)
WHERE {
    ?dataset_uri a dataid:Dataset ;
                 dataid:artifact <ARTIFACT_URI> ;
                 dcterms:hasVersion ?version .
    OPTIONAL { ?dataset_uri dcterms:issued ?issued . }
    OPTIONAL { ?dataset_uri dcat:distribution ?distribution_uri . }
}
GROUP BY ?version ?dataset_uri ?issued
ORDER BY DESC(?version)
