PREFIX schema: <http://schema.org/>
insert data {
  graph <http://kg.artsdata.ca/databus> {
    <http://kg.artsdata.ca/databus/capacoa/google-sheet/indigenous-performances> a <http://dataid.dbpedia.org/ns/core#Artifact> ;
      schema:name "Indigenous performances sheet" ;
      schema:potentialAction <http://kg.artsdata.ca/databus/capacoa/google-sheet/indigenous-performances#CreateAction>  .
    <http://kg.artsdata.ca/databus/capacoa/google-sheet/indigenous-performances#CreateAction>   a schema:CreateAction ;
      schema:name "Load spreadsheet of indigenous-performances" ;
      schema:target [
        a schema:EntryPoint ;
        schema:contentType "application/vnd.github.v3+json" ;
        schema:urlTemplate  "https://api.github.com/repos/culturecreates/artsdata-planet-scenepro/actions/workflows/scenepro-entities.yml/dispatches" ;
        schema:httpMethod "POST" ;
        schema:encodingType "application/json" ;
        schema:httpBody "{\"ref\":\"main\",\"inputs\":{\"prefix\":\"http://indigenous-performances/\",\"artifact\":\"indigenous-performances\",\"spreadsheet_url\":\"https://docs.google.com/spreadsheets/d/1dsaWJIEmcPmcbbXpEYPfgvPNSA60vEfpK1t1mxQjwiA/export?exportFormat=csv\",\"publisher\":\"{{PublisherWebID}}\"}}"  ] .
    }
}