PREFIX schema: <http://schema.org/>
PREFIX prov: <http://www.w3.org/ns/prov#>
select ?entities (count(?e) as ?PLACEHOLDERs)  ?dataset ?graph  ?generatedAtTime  where 
{
    ?graph a schema:Dataset .
    graph ?graph {
         ?e a ?type .
    }
    filter exists {
        ?e a schema:PLACEHOLDER  .
    } 
    ?graph rdfs:label ?dataset .
    OPTIONAL {
        ?graph prov:generatedAtTime ?generatedAtTime .
    }
    
    bind(ENCODE_FOR_URI(str(?dataset)) as ?dataset_escaped)
    bind(CONCAT("<a href='API?title=PLACEHOLDER entities in ",str(?dataset_escaped),"&sparql=SUB_SPARQL&placeholder=",str(?graph),"'>View</a>") as ?entities)
 
} group by ?graph ?dataset ?generatedAtTime ?entities order by DESC(?generatedAtTime)