PREFIX adr: <http://kg.artsdata.ca/resource/>
PREFIX schema: <http://schema.org/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
construct {
    ?event schema:name ?name .
    << ?event schema:name ?name >> ?a ?b .
     
    << ?event schema:name ?name >> schema:dataset ?graph .
    ?graph rdfs:label ?grap_label .
    
   schema:dataset rdfs:label "Dataset"@en .
} 
where {
    values ?event {
        <URI_PLACEHOLDER>
    }
    {
        graph ?graph {
            ?event schema:name ?name .
            OPTIONAL {
                <<?event schema:name ?name >> ?a ?b .
            }
             
        }
    }
    UNION
    {
        ?event  schema:sameAs ?sameAs .
        graph ?graph {
            ?sameAs schema:name ?name .
        }
    }
    UNION 
    {
        ?event  ^schema:sameAs ?sameAs .
        graph ?graph {
            ?sameAs schema:name ?name .
        }
    }

     ?graph rdfs:label ?grap_label .

}