PREFIX schema: <http://schema.org/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX void: <http://rdfs.org/ns/void#>
select ?entities (sample(?count) as ?organizations) ?dataset ?graph  ?generatedAtTime  where 
{
    ?graph a schema:Dataset .
    filter(!STRSTARTS(str(?graph),"http://kg.artsdata.ca/minted/K"))
    ?graph rdfs:label ?dataset;
           prov:generatedAtTime ?generatedAtTime ;
           prov:wasDerivedFrom/foaf:primaryTopic/void:classPortion  ?classPortion .
    ?classPortion void:class schema:Organization ;
             void:entities ?count .
    filter(?count > 0)
    bind(ENCODE_FOR_URI(str(?dataset)) as ?dataset_escaped)
    bind(CONCAT("<a href='/query/show?title=Organization entities in ",str(?dataset_escaped),"&sparql=list_organizations&graph=",str(?graph),"'>View</a>") as ?entities)
} group by ?entities  ?dataset ?graph  ?generatedAtTime order by DESC(?generatedAtTime)