PREFIX schema: <http://schema.org/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>

SELECT ?uri (sample(?name_language) as ?name)  (sample(?location_name) as ?location) (sample(?additionalType) as ?type)  ?startDateTime  (sample(?sameas_action) as ?artsdata) (sample(?resultSeverity) as ?conforms) 
WHERE {
    ?uri a schema:Event .
    graph <PLACEHOLDER> {
        ?uri schema:name  ?name_language ;
              a ?additionalType ;
             schema:startDate ?startDate . 
        bind(STRDT(str(?startDate),xsd:dateTime) as ?startDateTime)
       
        OPTIONAL {
            ?shacl sh:focusNode ?uri ;
                sh:resultSeverity ?resultSeverity .
        }
         OPTIONAL {
          ?uri a ?additionalType .
        }
    } 
    OPTIONAL {
      ?adid_sub schema:sameAs ?uri .
      filter(contains(str(?adid_sub),"http://kg.artsdata.ca/resource/K"))
    }

    OPTIONAL {
      ?uri schema:sameAs ?adid_obj .
      filter(contains(str(?adid_obj),"http://kg.artsdata.ca/resource/K"))
    }

    bind(COALESCE(?adid_obj, ?adid_sub) as ?adid)

    OPTIONAL {
        ?uri  schema:location/schema:name ?location_name .
    }

    BIND(COALESCE(?adid, "<button class='btn btn-primary btn-tiny' href='#'>mint</button>") as ?sameas_action)
   
    

} GROUP BY ?uri  ?startDateTime   
ORDER BY DESC(?startDateTime)