PREFIX schema: <http://schema.org/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
SELECT distinct ?uri (sample(?name_language) as ?name)  ?adid ?resultSeverity
WHERE {
    graph <PLACEHOLDER> {
        ?uri schema:name  ?name_language ;
             a ?type  . 
       
        OPTIONAL {
            ?shacl sh:focusNode ?uri ;
                sh:resultSeverity ?resultSeverity .
        }
         OPTIONAL {
            ?uri schema:sameAs ?adid .
            filter(contains(str(?adid),"http://kg.artsdata.ca/resource/K"))
        }
    }
    ?uri a schema:Person .      
    
    OPTIONAL {
      ?adid_sub schema:sameAs ?uri .
      filter(contains(str(?adid_sub),"http://kg.artsdata.ca/resource/K"))
    }

    OPTIONAL {
      ?uri schema:sameAs ?adid_obj .
      filter(contains(str(?adid_obj),"http://kg.artsdata.ca/resource/K"))
    }

    bind(COALESCE(?adid_obj, ?adid_sub) as ?adid)

    

} GROUP BY ?uri   ?resultSeverity ?adid
ORDER BY ?uri