# load_rdfstar_graph
# TODO: Add SHACL triples for blank nodes. Currently removed for performance crash when over 10 subevents (ville-de-laval)
# Modified to support lazy loading of annotations - does not load annotation details
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX onto: <http://www.ontotext.com/>
PREFIX schema: <http://schema.org/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
CONSTRUCT {
    ?s ?p ?o  .
    <<?s ?p ?o>> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://kg.artsdata.ca/ontology/HasAnnotations> .
    ?p rdfs:label ?prop_label .
    ?o rdfs:label ?obj_label .
    ?s ?p ?bns .
    ?bns ?bnp ?bno .
    ?bnp rdfs:label ?bnp_label .
    ?bns ?bnp ?2bns .
    ?2bns ?2bnp ?2bno .
    ?2bnp rdfs:label ?2bnp_label .
    ?2bns ?2bnp ?3bns .
    ?3bns ?3bnp ?3bno .
    ?shacl_bn sh:focusNode ?s ;
              ?shacl_pred ?shal_obj .
}
FROM onto:explicit 
WHERE {
    values ?s {
        <entity_uri_placeholder> 
    }
    {
        ?s ?p ?o  .
        # main triple labels
        OPTIONAL {
            ?o rdfs:label ?obj_label .
        }
        OPTIONAL {
            ?p rdfs:label ?prop_label .
        }
        OPTIONAL {
            ?o schema:name ?obj_name .
        }
        # Annotations are loaded lazily - just mark which triples have annotations without loading the details
        OPTIONAL {
            <<?s ?p ?o>> ?annotation_pred ?annotation_obj .
        }
        # blank nodes
        OPTIONAL {
            ?s ?p ?bns .
            filter(isBLANK(?bns))
            ?bns ?bnp ?bno .
            OPTIONAL {
                ?bnp rdfs:label ?bnp_label .
            }
            # second level blank nodes
            OPTIONAL {
                ?bns ?bnp ?2bns .
                filter(isBLANK(?2bns))
                ?2bns ?2bnp ?2bno .
                OPTIONAL {
                    ?2bnp rdfs:label ?2bnp_label .
                }
                # third level blank nodes
                OPTIONAL {
                    ?2bns ?2bnp ?3bns .
                    filter(isBLANK(?3bns))
                    ?3bns ?3bnp ?3bno .
                } 
            }
        }
    }
    UNION {
        OPTIONAL {
            ?shacl_bn sh:focusNode ?s ;
                      ?shacl_pred ?shal_obj .
        }
    }
} limit 1000