# replace_blank_nodes

DELETE {
 ?x ?y ?o .
  ?o ?a ?b .
 
}
INSERT {
 ?x ?y ?o_uri .
  ?o_uri ?a ?b .


}
WHERE {
  {
    SELECT distinct ?o  WHERE {
      ?s ?p ?o .
      filter(isBLANK(?o))
      filter(!isBLANK(?s)) # ?s can be a URI or a quoted triple for annotations.

    }

  }
   bind(URI(CONCAT("http://blank.node/",STRUUID())) as ?o_uri)
  ?x ?y ?o .
  ?o ?a ?b .
  
}