# replace_blank_subject_nodes

DELETE {
 ?s ?p ?o .
}
INSERT {
 ?s_uri ?p ?o .
}
WHERE {
  {
    {
      SELECT distinct ?s  WHERE {
        ?s ?a ?b .
        filter(isBLANK(?s))
        FILTER NOT EXISTS { ?s <http://www.w3.org/1999/xhtml/vocab#role> ?b }
        FILTER NOT EXISTS { ?any_subject ?any_predicate ?s }
      }
    
    }
    bind(URI(CONCAT("http://top.blank.node/",STRUUID())) as ?s_uri)
  }
  ?s ?p ?o .
 
 
}