DELETE {
    GRAPH <GRAPH_NAME_URI_PLACEHOLDER> {
        <SUBJECT_PLACEHOLDER> <PREDICATE_PLACEHOLDER> ?OBJECT_PLACEHOLDER .
        << <SUBJECT_PLACEHOLDER> <PREDICATE_PLACEHOLDER> ?OBJECT_PLACEHOLDER >> ?a ?b .
        ?b ?bp ?bo .
        # OBJECT_CASCADE_DELETE_PLACEHOLDER
    }

}
WHERE {
    GRAPH <GRAPH_NAME_URI_PLACEHOLDER> {
        # PATH_WHERE_PLACEHOLDER
        <SUBJECT_PLACEHOLDER> <PREDICATE_PLACEHOLDER> ?OBJECT_PLACEHOLDER .
        OPTIONAL {
            << <SUBJECT_PLACEHOLDER> <PREDICATE_PLACEHOLDER> ?OBJECT_PLACEHOLDER >> ?a ?b .
            OPTIONAL {
                ?b ?bp ?bo .
                FILTER(isBlank(?b))
            }
        }
        # OBJECT_CASCADE_WHERE_PLACEHOLDER
    }
}
