DELETE {
    GRAPH <GRAPH_NAME_URI_PLACEHOLDER> {
        <SUBJECT_PLACEHOLDER> <PREDICATE_PLACEHOLDER> <OBJECT_PLACEHOLDER> .
        << <SUBJECT_PLACEHOLDER> <PREDICATE_PLACEHOLDER> <OBJECT_PLACEHOLDER> >> ?a ?b .
        ?b ?bp ?bo .
    }
}
WHERE {
    GRAPH <GRAPH_NAME_URI_PLACEHOLDER> {
        <SUBJECT_PLACEHOLDER> <PREDICATE_PLACEHOLDER> <OBJECT_PLACEHOLDER> .
        OPTIONAL {
            << <SUBJECT_PLACEHOLDER> <PREDICATE_PLACEHOLDER> <OBJECT_PLACEHOLDER> >> ?a ?b .
            OPTIONAL {
                ?b ?bp ?bo .
                FILTER(isBlank(?b))
            }
        }
    }
}
