PREFIX void: <http://rdfs.org/ns/void#>
PREFIX schema: <http://schema.org/>
construct {
    ?id  void:inDataset ?source_graph .
    ?source_graph schema:name ?picked_name .
    ?source_graph schema:ratingValue ?rank .
}
where {
    values ?id {
        <entity_uri_placeholder>
    }
    {
        ?id void:inDataset ?source_graph .
        ?source_graph schema:contentRating ?rating .
        ?rating schema:ratingValue ?rank .
    } 
    UNION 
    {
        graph ?source_graph {
            ?id a ?type .
        }
    }
    OPTIONAL {
        ?source_graph schema:name ?name .
    }
    BIND(COALESCE(?name, str(?source_graph)) as ?picked_name)
}