DELETE {
    GRAPH <GRAPH_NAME_URI_PLACEHOLDER> {
        <<<BASE_SUBJECT_PLACEHOLDER> <BASE_PREDICATE_PLACEHOLDER> ?BASE_OBJECT_PLACEHOLDER>> <OLD_PREDICATE_PLACEHOLDER> ?ANNOTATION_OBJECT_PLACEHOLDER .
    }
}
INSERT {
    GRAPH <GRAPH_NAME_URI_PLACEHOLDER> {
        <<<BASE_SUBJECT_PLACEHOLDER> <BASE_PREDICATE_PLACEHOLDER> ?BASE_OBJECT_PLACEHOLDER>> <NEW_PREDICATE_PLACEHOLDER> ?ANNOTATION_OBJECT_PLACEHOLDER .
    }
}
WHERE {
    GRAPH <GRAPH_NAME_URI_PLACEHOLDER> {
        # PATH_WHERE_PLACEHOLDER
        <<<BASE_SUBJECT_PLACEHOLDER> <BASE_PREDICATE_PLACEHOLDER> ?BASE_OBJECT_PLACEHOLDER>> <OLD_PREDICATE_PLACEHOLDER> ?ANNOTATION_OBJECT_PLACEHOLDER .
    }
}
