PREFIX schema: <http://schema.org/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
SELECT ?uri (sample(?name_language) as ?name) ?url  (sample(?adid) as ?sameAs) (sample(?resultSeverity) as ?conforms) WHERE {
    graph <http://kg.artsdata.ca/culture-creates/huginn/capacoa-members> {
        values ?type {schema:Organization schema:Person}
        ?uri schema:name  ?name_language ;
             a ?type .
        OPTIONAL {
            ?uri schema:url ?url .
            filter(!isBLANK(?url))
        }
        OPTIONAL {
            ?uri   schema:sameAs ?adid .
            filter(contains(str(?adid),"http://kg.artsdata.ca/"))
        }
       
        OPTIONAL {
            ?shacl sh:focusNode ?uri ;
                sh:resultSeverity ?resultSeverity .
        }
    }
     OPTIONAL {
            ?uri  ^schema:sameAs ?adid .
            filter(contains(str(?adid),"http://kg.artsdata.ca/"))
        }
} GROUP BY ?uri  ?url  