PREFIX schema: <http://schema.org/>
PREFIX prov: <http://www.w3.org/ns/prov#>
select  ?entity ?name ?ipaa_type  ?webpage ?coalesce_adid ?coalesce_wdid where {
    graph <http://kg.artsdata.ca/culture-creates/artsdata-planet-ipaa/ipaa-entities> {
        values ?ipaa_type {
            schema:Organization  schema:Person
        } 
        ?entity a ?ipaa_type ;
                schema:name ?name .
        filter(!isBlank(?entity))
        ?entity prov:wasDerivedFrom ?webpage .
       
    }
    OPTIONAL {
            ?entity schema:sameAs ?ipaa_adid .
        	filter(strstarts(str(?ipaa_adid),"http://kg.artsdata.ca/resource/K"))
            OPTIONAL {
            ?ipaa_adid schema:sameAs ?ad_wdid .
             filter(strstarts(str(?ad_wdid),"http://www.wikidata.org/entity/Q"))
        }
        }
    OPTIONAL {
            ?entity schema:sameAs ?ipaa_wdid .
        	filter(strstarts(str(?ipaa_wdid),"http://www.wikidata.org/entity/Q"))
        }
    OPTIONAL {
            ?entity schema:sameAs/^schema:sameAs ?wdid .
          
        	filter(strstarts(str(?wdid),"http://www.wikidata.org/entity/Q"))
        }
    OPTIONAL {
        ?adid schema:sameAs ?entity .
        filter(strstarts(str(?adid),"http://kg.artsdata.ca/resource/K"))
        OPTIONAL {
            ?adid schema:sameAs ?ad_wdid .
             filter(strstarts(str(?ad_wdid),"http://www.wikidata.org/entity/Q"))
        }
    }
    OPTIONAL {
        ?adid schema:sameAs ?entity .
        filter(strstarts(str(?adid),"http://kg.artsdata.ca/resource/K"))
        OPTIONAL {
           ?ad_wdid  schema:sameAs ?adid .
             filter(strstarts(str(?ad_wdid),"http://www.wikidata.org/entity/Q"))
        }
    }
    
    bind(COALESCE(?wdid,?ad_wdid,?ipaa_wdid) as ?coalesce_wdid)
    bind(COALESCE(?adid,?ipaa_adid) as ?coalesce_adid)

    
    
}