PREFIX schema: <http://schema.org/>
PREFIX adm: <http://kg.artsdata.ca/minted/>
select ?artsdata (sample(?names) as ?name) ?wikidata ?postalCode (sample(?regions) as ?region)  (sample(?localities) as ?locality)where {
    values ?graph {
        adm:K5 adm:K2 adm:K4 adm:K11 adm:K13 adm:K16  
    }
    graph ?graph {
        ?artsdata a schema:Place ;
                  schema:name ?names ;
                  schema:address/schema:addressRegion  ?regions ;
                  schema:address/schema:addressLocality  ?localities ;
                  schema:address/schema:postalCode  ?postalCode ;
                  schema:address/schema:addressCountry ?country .
        filter(str(?country) = "CA")
    }
    optional {
        ?artsdata schema:sameAs ?wikidata .
        filter(strstarts(str(?wikidata),"http://www.wikidata.org/entity"))
    }
}  group by ?artsdata ?wikidata  ?postalCode