PREFIX schema: <http://schema.org/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
SELECT ?uri (sample(?name_language) as ?scenepro_name) ?aduri  (sample(?artsdata_name_language) as ?artsdata_name) (sample(?wduri) as ?wikidata)  ?url ?resultSeverity  WHERE {
    graph <http://kg.artsdata.ca/culture-creates/huginn/scenepro-orgs> {
        ?uri schema:name  ?name_language ;
             a schema:Place .
        OPTIONAL {
            ?uri schema:url ?url .
            filter(!isBLANK(?url))
        }
        OPTIONAL {
            ?shacl sh:focusNode ?uri ;
                sh:resultSeverity ?resultSeverity .
        }
       
    }
   
     OPTIONAL {
            ?aduri schema:sameAs ?uri ; schema:name ?artsdata_name_language .
            filter(contains(str(?aduri),"http://kg.artsdata.ca/"))
            OPTIONAL {
                ?wduri4 schema:sameAs ?aduri .
                filter(contains(str(?wduri4),"wikidata.org/"))
            }
             OPTIONAL {
                ?aduri schema:sameAs ?wduri4 .
                filter(contains(str(?wduri4),"wikidata.org/"))
            }
        }
       

        bind(COALESCE(?wduri2, ?wduri3, ?wduri4, ?wduri1) as ?wduri)
        
} GROUP BY ?uri ?aduri  ?url  ?resultSeverity