PREFIX schema: <http://schema.org/>
PREFIX ex: <http://www.example.org#>
construct {
    ?scenepro   a schema:Organization ;
                a ex:SceneproEntity ;
                schema:name ?scenepro_name ;
                schema:sameAs ?adid ;
                schema:sameAs ?wikidata ;
                ex:neq ?neq ;
                schema:telephone ?telephone ;   
                schema:url ?url ;   
                ex:address ?address ;       
                ex:postalCode ?postalCode ; 
                ex:addressLocality ?addressLocality .

    ?adid a ex:ArtsdataEntity ;
              schema:sameAs ?scenepro .   
    ?wikidata a ex:WikidataEntity ;
                schema:sameAs ?scenepro .
}
where {
    # ScenePro organizations that may have a sameAs Artsdata organization
    ?scenepro a schema:Organization ;
              schema:name ?scenepro_name .
    filter(strstarts(str(?scenepro),"http://scenepro.ca#Organization"))
    OPTIONAL {
        ?scenepro schema:sameAs ?adid .
        filter(strstarts(str(?adid),"http://kg.artsdata.ca/resource/K"))
    }
    OPTIONAL {
        ?scenepro schema:sameAs ?wikidata .
        filter(strstarts(str(?wikidata),"http://www.wikidata.org/entity/Q"))
    }
    optional {
        ?scenepro schema:telephone ?telephone .
    }
     optional {
        ?scenepro schema:url ?url .
    }
     optional {
        ?scenepro schema:address/schema:streetAddress ?address .
    }
      optional {
        ?scenepro schema:address/schema:postalCode ?postalCode .
    }
      optional {
        ?scenepro schema:address/schema:addressLocality ?addressLocality .
    }
     optional {
        ?scenepro <http://www.wikidata.org/prop/direct/P10503> ?neq .
    }
}