PREFIX schema: <http://schema.org/>
PREFIX ex: <http://www.example.org#>
select * where {
    {
        values ?note {
            "Artsdata lead"
        }
        FILTER NOT EXISTS {
            ?something schema:sameAs ?adid 
        }
        ?adid a ex:ArtsdataEntity ;
              schema:name ?ad_name .
        OPTIONAL {
            ?adid schema:sameAs ?scenepro .
            ?scenepro a ex:SceneproEntity .
        }
        OPTIONAL {
            ?adid schema:sameAs ?wikidata .
            ?wikidata a  ex:WikidataEntity .
        }
        OPTIONAL {
            ?adid schema:sameAs ?wikidata .
            ?wikidata schema:name ?wikidata_name .
            ?wikidata a ex:WikidataEntity .
        }
        OPTIONAL {
            ?adid schema:sameAs ?wikidata .
            ?wikidata ex:SceneProMemberStatedInLabel ?wdr_statedIn .
            ?wikidata a ex:WikidataEntity .
        }
        OPTIONAL {
            ?adid schema:sameAs ?wikidata .
            ?wikidata  ex:SceneProMemberRetreivedDate ?wdr_RetreivedDate  .
            ?wikidata a ex:WikidataEntity .
        }
    } 
    UNION 
    {
        values ?note {
            "Wikidata lead"
        }
        ?wikidata a ex:WikidataEntity .
        FILTER NOT EXISTS {
            ?another schema:sameAs ?wikidata 
        }
        OPTIONAL {
            ?wikidata schema:name ?wikidata_name .
            ?wikidata a ex:WikidataEntity .
        }
        OPTIONAL {
            ?wikidata ex:SceneProMemberStatedInLabel ?wdr_statedIn .
            ?wikidata a ex:WikidataEntity .
        }
        OPTIONAL {
            ?wikidata  ex:SceneProMemberRetreivedDate ?wdr_RetreivedDate  .
            ?wikidata a ex:WikidataEntity .
        }
        OPTIONAL {
            ?wikidata  schema:sameAs ?adid  .
            ?wikidata a ex:WikidataEntity .
            ?adid a ex:ArtsdataEntity .
        }
    } 
    UNION 
    {
        values ?note {
            "Scenepro lead"
        }
        ?scenepro a ex:SceneproEntity .
        # FILTER NOT EXISTS {
        #     ?b schema:sameAs ?scenepro 
        # }
        OPTIONAL {
            values ?member {"scenepro API"}
            graph <http://kg.artsdata.ca/culture-creates/huginn/scenepro-orgs> {
                ?scenepro a schema:Organization .
            }
        }
        OPTIONAL {
            ?scenepro schema:name ?scenepro_name .
            ?scenepro a ex:SceneproEntity .
        }
        OPTIONAL {
            ?scenepro schema:sameAs ?adid .
            ?adid a ex:ArtsdataEntity .
        }
        OPTIONAL {
            ?scenepro schema:sameAs ?wikidata .
            ?wikidata a  ex:WikidataEntity .
        }
        OPTIONAL {
            ?scenepro schema:sameAs ?wikidata .
            ?wikidata schema:name ?wikidata_name .
            ?wikidata a ex:WikidataEntity .
        }
        OPTIONAL {
            ?scenepro schema:sameAs ?wikidata .
            ?wikidata ex:SceneProMemberStatedInLabel ?wdr_statedIn .
            ?wikidata a ex:WikidataEntity .
        }
        OPTIONAL {
            ?scenepro schema:sameAs ?wikidata .
            ?wikidata  ex:SceneProMemberRetreivedDate ?wdr_RetreivedDate  .
            ?wikidata a ex:WikidataEntity .
        }
    }
}