PREFIX schema: <http://schema.org/>
select * where {
    ?Artsdata a schema:Place ;
          schema:sameAs ?sceneproId .
    ?sceneproId schema:name ?sceneproName .
    filter(contains(str(?sceneproId),"http://scenepro.ca#Venue"))
    filter(contains(str(?Artsdata),"http://kg.artsdata.ca/resource/K"))
    OPTIONAL {
        values ?note {
            "Incorrect ScenePro SameAs to Artsdata "
        }
        ?sceneproId schema:sameAs ?anotherAD
        filter(contains(str(?anotherAD),"http://kg.artsdata.ca/resource/K"))
        filter(Bound(?anotherAD))
        filter( ?Artsdata != ?anotherAD )
    }
    OPTIONAL {
        ?Artsdata schema:sameAs ?ADWDid .
        filter(contains(str(?ADWDid),"http://www.wikidata.org/entity/Q"))
    }
    OPTIONAL {
        ?sceneproId schema:sameAs ?SPWDid .
        filter(contains(str(?SPWDid),"http://www.wikidata.org/entity/Q"))
    }
    OPTIONAL {
        ?sceneproId schema:address/schema:addressCountry ?country .
    }


    OPTIONAL {
        ?sceneproId schema:address/schema:addressLocality ?locality .
    } 
    OPTIONAL {
        ?sceneproId schema:telephone ?phone .
    }


    OPTIONAL {
        ?sceneproId schema:address/schema:addressRegion ?region .
    } OPTIONAL {
        ?sceneproId schema:address/schema:postalCode ?postalCode .
    } OPTIONAL {
        ?sceneproId schema:address/schema:streetAddress ?streetAddress .
    } 
    BIND(CONCAT(?streetAddress,", ",?locality,", ",?region,", ",?postalCode) as ?fullAddress)
    
    OPTIONAL {
        ?sceneproId schema:subjectOf/schema:url ?urlTechSpec .
    }
    OPTIONAL {
       ?sceneproId schema:maximumAttendeeCapacity ?capacity .
       filter(?capacity != "0")  
    }

}