 CONSTRUCT { 
        <EXTERNAL_URI> a schema:Organization ; 
        schema:name ?name ; 
        schema:sameAs ?aduri ;
        schema:description ?desc ;
        schema:url ?url ;
        schema:location ?country, ?territory;
        schema:sameAs ?isni, ?spotify_artist, ?music_brainz .
      } 
      WHERE { 
        <EXTERNAL_URI> <http://www.w3.org/2000/01/rdf-schema#label> ?name . 
        filter (lang(?name) = 'en' || lang(?name) = 'fr')

        OPTIONAL { 
          <EXTERNAL_URI>  schema:description ?desc . 
          filter (lang(?desc) = 'en' || lang(?desc) = 'fr') 
        }
         OPTIONAL { 
          <EXTERNAL_URI>  <http://www.wikidata.org/prop/direct/P17>  ?country . 
        }
        OPTIONAL { 
          <EXTERNAL_URI>  <http://www.wikidata.org/prop/direct/P131>  ?territory . 
        }
          
        OPTIONAL { 
          <EXTERNAL_URI> <http://www.wikidata.org/prop/direct/P7627> ?adid  .
          BIND (URI(CONCAT("http://kg.artsdata.ca/resource/",?adid)) as ?aduri) 
        }
        OPTIONAL { <EXTERNAL_URI> <http://www.wikidata.org/prop/direct/P856> ?url .}
        OPTIONAL { 
          <EXTERNAL_URI> <http://www.wikidata.org/prop/direct/P213> ?isni_id .
          BIND (URI(CONCAT("https://isni.org/isni/",?isni_id)) as ?isni)
        }
        OPTIONAL { 
          <EXTERNAL_URI> <http://www.wikidata.org/prop/direct/P1902> ?spotify_artist_id .
          BIND (URI(CONCAT("https://open.spotify.com/artist/",?spotify_artist_id)) as ?spotify_artist)
        }
        OPTIONAL { <EXTERNAL_URI> <http://www.wikidata.org/prop/direct-normalized/P434> ?music_brainz .}
      }