PREFIX schema: <http://schema.org/>
PREFIX ado: <http://kg.artsdata.ca/ontology/>
select ?log_date ?action ?source ?property ?value  where {
    ?action_bn ado:refreshPredicate ?property ; ado:refreshObject ?value ; ado:refreshSource ?source .
    ?log_entry ?action ?action_bn .
    ?log_entry schema:dateCreated ?log_date .
    ?log ado:hasActivityLog ?log_entry .
    ?log schema:about <URI_PLACEHOLDER> .
} order by DESC(?log_date)  ?property